
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatter;
import models.BookProduct;
import models.MovieProduct;
import models.MusicProduct;
import models.Product;
import viewmodel.ProductDAO;
import viewmodel.ProductDAOImpl;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ling
 */
public class UpdateProduct extends javax.swing.JFrame {

    List<Product> listProduct;
    DefaultTableModel dtm = null;
    public UpdateProduct() {
        ProductDAO pdDAO = new ProductDAOImpl();
        listProduct = pdDAO.showAll();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(195, 10));
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabel1.setText("Update Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 0, 280, 60));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setRequestFocusEnabled(false);
        jButton4.setVerifyInputWhenFocusTarget(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 45, 45));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 960, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, 960, 545));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 500, 40));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setLabel("Sách");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 70, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jRadioButton2.setLabel("Đĩa phim");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 70, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jRadioButton3.setLabel("Đĩa nhạc");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        String title[] = {"ID sản phẩm","Tên sản phẩm", "Số lượng", "Giá nhập", "Giá bán", "Loại", "Thể loại", "Tác giả", "Nhà xuất bản", "Dịch giả"};
        dtm = new DefaultTableModel(null, title);
        
        String data[][] = new String[1][10];
        for (Product pd : listProduct){
            if (pd instanceof BookProduct bookProduct){
                bookProduct.output();
                data[0][0] = String.valueOf(bookProduct.getID());
                data[0][1] = bookProduct.getName();
                data[0][2] = String.valueOf(bookProduct.getAmount());
                data[0][3] = String.valueOf(bookProduct.getInPrice());
                data[0][4] = String.valueOf(bookProduct.getOutPrice());
                data[0][5] = bookProduct.getType();
                data[0][6] = bookProduct.getCategory();
                data[0][7] = bookProduct.getAuthor();
                data[0][8] = bookProduct.getPublisher();
                data[0][9] = bookProduct.getTranslator();
                dtm.addRow(data[0]);
            }
        }
        jTable1.setModel(dtm);
    }//GEN-LAST:event_formComponentShown
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        String title[] = {"ID sản phẩm","Tên sản phẩm", "Số lượng", "Giá nhập", "Giá bán", "Loại", "Thể loại", "Tác giả", "Nhà xuất bản", "Dịch giả"};
        dtm = new DefaultTableModel(null, title);
        
        String data[][] = new String[1][10];
        for (Product pd : listProduct){
            if (pd instanceof BookProduct bookProduct){
                bookProduct.output();
                data[0][0] = String.valueOf(bookProduct.getID());
                data[0][1] = bookProduct.getName();
                data[0][2] = String.valueOf(bookProduct.getAmount());
                data[0][3] = String.valueOf(bookProduct.getInPrice());
                data[0][4] = String.valueOf(bookProduct.getOutPrice());
                data[0][5] = bookProduct.getType();
                data[0][6] = bookProduct.getCategory();
                data[0][7] = bookProduct.getAuthor();
                data[0][8] = bookProduct.getPublisher();
                data[0][9] = bookProduct.getTranslator();
                dtm.addRow(data[0]);
            }
        }
        jTable1.setModel(dtm);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        String title[] = {"ID sản phẩm","Tên sản phẩm", "Số lượng", "Giá nhập", "Giá bán", "Loại", "Thể loại", "Đạo diễn", "Nhà sản xuất"};
        dtm = new DefaultTableModel(null, title);
        
        String data[][] = new String[1][9];
        for (Product pd : listProduct){
            if (pd instanceof MovieProduct movieProduct){
                data[0][0] = String.valueOf(movieProduct.getID());
                data[0][1] = movieProduct.getName();
                data[0][2] = String.valueOf(movieProduct.getAmount());
                data[0][3] = String.valueOf(movieProduct.getInPrice());
                data[0][4] = String.valueOf(movieProduct.getOutPrice());
                data[0][5] = movieProduct.getType();
                data[0][6] = movieProduct.getCategory();
                data[0][7] = movieProduct.getAuthor();
                data[0][8] = movieProduct.getDirector();
                dtm.addRow(data[0]);
            }
        }
        
        jTable1.setModel(dtm);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        String title[] = {"ID sản phẩm","Tên sản phẩm", "Số lượng", "Giá nhập", "Giá bán", "Loại", "Thể loại", "Ca sĩ", "Ban nhạc", "Nhà sản xuất"};
        dtm = new DefaultTableModel(null, title);
        
        String data[][] = new String[1][10];
        for (Product pd : listProduct){
            if (pd instanceof MusicProduct musicProduct){
                data[0][0] = String.valueOf(musicProduct.getID());
                data[0][1] = musicProduct.getName();
                data[0][2] = String.valueOf(musicProduct.getAmount());
                data[0][3] = String.valueOf(musicProduct.getInPrice());
                data[0][4] = String.valueOf(musicProduct.getOutPrice());
                data[0][5] = musicProduct.getType();
                data[0][6] = musicProduct.getCategory();
                data[0][7] = musicProduct.getSinger();
                data[0][8] = musicProduct.getBand();
                data[0][9] = musicProduct.getProducer();
                dtm.addRow(data[0]);
            }
        }
        
        jTable1.setModel(dtm);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ProductDAO pdDAO = new ProductDAOImpl();
        boolean sach = jRadioButton1.isSelected();
        boolean diaPhim = jRadioButton2.isSelected();
        boolean diaNhac = jRadioButton3.isSelected();
        int columnCount = jTable1.getColumnCount();
        int rowCount = jTable1.getRowCount();
        String data[] = new String[columnCount];
        Product product;
        if (sach == true){
            for (int i = 0; i < rowCount; i++){
                for (int j = 0; j < columnCount; j++){
                    data[j] = String.valueOf(jTable1.getValueAt(i, j));
                }
                //ID sản phẩm","Tên sản phẩm", "Số lượng", "Giá nhập", "Giá bán", "Loại", "Thể loại", "Tác giả", "Nhà xuất bản", "Dịch giả"};
                //String name, int amount,int inPrice, int outPrice , String type, String category , String publisher, String author, String translator){
                product = new BookProduct(data[1], Integer.valueOf(data[2]), Integer.valueOf(data[3]), Integer.valueOf(data[4]), data[5], data[6], data[8], data[7], data[9]);
                product.setID(Integer.valueOf(data[0]));
                pdDAO.update(product);
            }
        }
        if (diaPhim == true){
            for (int i = 0; i < rowCount; i++){
                for (int j = 0; j < columnCount; j++){
                    data[j] = String.valueOf(jTable1.getValueAt(i, j));
                }
                //"ID sản phẩm","Tên sản phẩm", "Số lượng", "Giá nhập", "Giá bán", "Loại", "Thể loại", "Đạo diễn", "Nhà sản xuất
                //String name, int amount, int inPrice, int outPrice, String type, String category, String author, String director
                product = new MovieProduct(data[1], Integer.valueOf(data[2]), Integer.valueOf(data[3]), Integer.valueOf(data[4]), data[5], data[6], data[7], data[8]);
                product.setID(Integer.valueOf(data[0]));
                pdDAO.update(product);
            }
        }
        if (diaNhac == true){
            for (int i = 0; i < rowCount; i++){
                for (int j = 0; j < columnCount; j++){
                    data[j] = String.valueOf(jTable1.getValueAt(i, j));
                }
                //"ID sản phẩm","Tên sản phẩm", "Số lượng", "Giá nhập", "Giá bán", "Loại", "Thể loại", "Ca sĩ", "Ban nhạc", "Nhà sản xuất"
                //String name, int amount, int inPrice, int outPrice, String type,String category, String singer, String producer, String band
                product = new MusicProduct(data[1], Integer.valueOf(data[2]), Integer.valueOf(data[3]), Integer.valueOf(data[4]), data[5], data[6], data[7], data[9], data[8]);
                product.setID(Integer.valueOf(data[0]));
                pdDAO.update(product);
            }
        }
        JOptionPane.showMessageDialog(null, "Thay đổi thành công!");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
